### ISSUE TITLE
Bug on login

### ISSUE THREAD

**Issue by ms3056** [mountfarmer/Name2Chat#1]
Hello - I am very happy someone has taken this mod up again. Unfortunately, it is not working for me:

```
Message: AceLocale-3.0: Name2Chat: Missing entry for 'name'
Time: 03/04/17 12:05:12
Count: 1
Stack: Interface\AddOns\Name2Chat\Name2Chat.lua:26: in main chunk

Locals: L = <table> {
 name = "name"
}
(*temporary) = <table> {
 type = "group"
 set = <function> defined @Interface\AddOns\Name2Chat\Name2Chat.lua:21
 get = <function> defined @Interface\AddOns\Name2Chat\Name2Chat.lua:20
}
(*temporary) = <table> {
}
(*temporary) = <table> {
 order = 1
 type = "input"
}
(*temporary) = <table> {
 name = "name"
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
```

This is on login. None of the commands are working. /name2chat and /n2c do not work. The mod does not show up in the interface options either.

**Comment by gOOvER** [comment]
Hmmm can't confirm...

What language is the Client?

**Comment by DesertDwarf** [comment]
I have the same problem.

I don't know if it's related, but my \Interface\AddOns\Name2Chat\lang\enUS.lua is completely empty. I have 12 other addons that have enUS.lua files and none of the rest of them are empty.

**Comment by DesertDwarf** [comment]
I just copied the enUS.lua file (which is not empty) from github here and put it in the right place, did a reloadui, and no more error and Name2Chat now shows up.

I got my copy of Name2Chat from Twitch app, which pulls from the Curse site. Somehow, that one has an empty enUS.lua file.

**Comment by SoulCookie** [comment]
@gOOvER: I can echo @DesertDwarf's observations:

- Installed Name2Chat from Twitch/Curse
- Logged in; got error message; addon is un-configurable & doesn't appear in interface options
- Downloaded a copy of `enUS.lua` from here on Github and overwrote existing (empty) version
- **Success!** Name2Chat is now working without a problem.

**Comment by gOOvER** [comment]
I will take a look Ingo. normally all lang Files will Added by curse

**Comment by gOOvER** [comment]
can you try the latest 1.2.0-beta pls??

**Comment by DesertDwarf** [comment]
No change.

![image](https://user-images.githubusercontent.com/39987/27008213-7c3f1b72-4e20-11e7-8887-a92e3349da50.png)

**Comment by DesertDwarf** [comment]
No change. :-(

![image](https://user-images.githubusercontent.com/39987/27008223-d994fd28-4e20-11e7-9ff2-9ed6ba832313.png)

**Comment by DesertDwarf** [comment]
Just to be thorough, I manually downloaded 1.2.0-beta and the enUS.lua file was 0 bytes. I also downloaded 1.0.0 from WowInterface and the unUS.lua file was also 0 bytes.

Somehow, when you are uploading it, you are uploading a 0 byte version of the file.

**Comment by gOOvER** [comment]
i Upload nothing. Thats zur Problem. Curse is triggert from Github, when i commit a change. Then Curse pulls the Code from github

**Comment by gOOvER** [comment]
i will investigate :)

**Comment by gOOvER** [comment]
Should be fixed in latestet Beta :)
