### ISSUE TITLE
Can't type in chat

### ISSUE THREAD

**Issue by Musashi58** [Mountfarmer/Name2Chat#3]
When Name2chat is on in addons you can't type in chatt, if you turn it off it works again, i do like it so i want it to work.

**Comment by gOOvER** [comment]
I don't know, whats happend. I investigate atm. Pls click on guild in options, then you can write again as fast fix.

**Comment by gOOvER** [comment]
Should be fixed with:

**Comment by gOOvER** [comment]
Should be fixed with 2.0.3:

https://github.com/Mountfarmer/Name2Chat/commit/f9946df6daa050ddcd3e3f665a83256c2600d125

I pushed testing changes and forget to remove them :D
